# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
---
title: Steven McFarlane's Blog
name: Steven McFarlane's Blog
email: stevemac72@gmail.com
description: >
  Welcome to the mussings of Steven Mcfarlane
baseurl: "/"
url: "https://smcfarlane.github.io"
twitter_username: steven_mcfarlane
github_username: smcfarlane
paginate: 10

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
